FROM node:20-alpine

# Ishchi katalog
WORKDIR /app

# Bog'liqliklarni o'rnatish
COPY package*.json ./
RUN npm install

# Barcha kodni nusxalash
COPY . .

# Development uchun ishga tushirish (ts-node-dev yoki nodemon)
# NestJS'da bu odatda 'npm run start:dev'
CMD ["npm", "run", "start:dev"]